amp_dtype: bfloat16
batch_size: 8
checkpoint_dir: checkpoints/experiment
data_dir: data/groundcap
device: null
early_stopping_min_delta: 0.01
early_stopping_patience: 3
generate_samples_every_n_epochs: 1
gradient_clip_val: 0.3
learning_rate: 1.0e-05
log_dir: logs/experiment
log_every_n_steps: 10
min_lr: 1.0e-06
num_epochs: 12
num_validation_samples: 3
num_workers: 4
resume_from_checkpoint: null
save_every_n_epochs: 1
scheduler_type: cosine
use_amp: true
use_early_stopping: true
use_scheduler: true
val_every_n_epochs: 1
weight_decay: 0.01
